### ISSUE TITLE
分区建议

### ISSUE THREAD

**Issue by phone-burner** [NekokeCore/edk2-dipper#2]
感觉/cust分区没用
cust主要用来存储预安装软件（喜马拉雅、高德地图等等），可以格式化以后存储数据，有差不多800MB的空间可以使用。
如果担心里面的系统应用，可以把分区缩减到100MB，加一个分区

**Comment by sunshinewithmoonlight** [comment]
> 感觉/cust分区没用
> cust主要用来存储预安装软件（喜马拉雅、高德地图等等），可以格式化以后存储数据，有差不多800MB的空间可以使用。
> 如果担心里面的系统应用，可以把分区缩减到100MB，加一个分区

你好，
请问这里的XiaomiMI8Pkg 里面的文件在哪里找的吗？
怎么找其他手机的包啊，比方说联发科平台的？
