### ISSUE TITLE
Guide for other sdm845 devices

### ISSUE THREAD

**Issue by mhtygt211227** [NekokeCore/edk2-dipper#4]
İ have oneplus 6 which is too similar mi8 .that will be great a guide for edk2 porting and deploying ? And maybe a telegram group?

**Comment by strongtz** [comment]
@mhtygt211227  Sorry, but currently we only have a development group on a Chinese social media.

**Comment by strongtz** [comment]
@mhtygt211227 
You are welcomed to make a pull request here. https://github.com/edk2-porting/edk2-sdm845 
BTW, here is our new telegram group. https://t.me/joinchat/MNjTmBqHIokjweeN0SpoyA
