### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by marohinmark** [NekokeCore/edk2-dipper#6]
![Screenshot from 2021-04-22 20-25-03](https://user-images.githubusercontent.com/70785816/115813862-d9de7480-a3a8-11eb-9126-4ff916defa61.png)

**Comment by strongtz** [comment]
You may want to have a look at this:
[edk2-sdm845](https://github.com/edk2-porting/edk2-sdm845)

Unfortunately USB is currently unavailable on dipper

**Comment by marohinmark** [comment]
I fixed it  (it is not USB error, I just needed a libraryclass in dsc file)
